- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes
    - name: Clone github repository
      git:
        repo: https://github.com/ShireenAzad/EmployeePortal.git
        dest: /home/ubuntu/app/
        clone: yes
        force: yes
        update: yes
    - name: Installing maven
      ansible.builtin.shell:
        cmd: sudo apt install maven 

    - name: Installing npm
      ansible.builtin.shell:
        cmd: sudo apt install npm 

    - name: Running the Spring Boot Application
      ansible.builtin.shell:
        chdir: /home/ubuntu/app/src/main/java/com/everestengineering/employeeportalapplication/
        cmd: nohup mvn spring-boot:run &
    - name: Installing node modules
      ansible.builtin.shell:
        chdir: /home/ubuntu/app/frontend/src
        cmd:  npm install |  npm start
  