- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    
    - name: Update apt packages
      ansible.builtin.shell:
        cmd: sudo apt update
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes
    - name: Clone github repository
      git:
        repo: https://github.com/ShireenAzad/EmployeePortal.git
        dest: /home/ubuntu/app/
        clone: yes
        force: yes
        update: yes
   
    - name: Installing nodejs
      ansible.builtin.shell:
        cmd: sudo apt install curl -y | sudo apt policy nodejs
    - name: Installing npm
      ansible.builtin.shell:
        cmd: curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash - |  sudo apt-get install nodejs
    - name: Installing pm
      ansible.builtin.shell:
        cmd: npm install pm2 -g
    - name: Installing maven
      ansible.builtin.shell:
        cmd: sudo apt install maven -y
    - name: Running the Spring Boot Application
      ansible.builtin.shell:
        chdir: /home/ubuntu/app/src/main/java/com/everestengineering/employeeportalapplication/
        cmd:  nohup mvn spring-boot:run -Dspring-boot.run.arguments="--spring.datasource.url=jdbc:postgresql://process.env.ENDPOINT/employee" & > ../nohup.out
    - name: Installing node modules
      ansible.builtin.shell:
        chdir: /home/ubuntu/app/frontend/src/
        cmd:  npm install 
    - name: Installing node modules
      ansible.builtin.shell:
        chdir: /home/ubuntu/app/frontend/src/
        cmd: npm install dotenv --save
    - name: Installing node modules
      ansible.builtin.shell:
        chdir: /home/ubuntu/app/frontend/src/
        cmd: npm audit fix
    - name: Building
      ansible.builtin.shell:
        chdir: /home/ubuntu/app/frontend/
        cmd: REACT_APP_BASE_URL="{{ PUBLIC_IP }}" pm2 start npm -- start
   